### ISSUE TITLE
Hint syntax check / new syntax?

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz-parser#1]
Right now the correct syntax for hints are
```
hint 'first hint' 'second hint' 'etc'
```
Writing 
```
hint 'first hint'
hint 'second hint'
```
will not result in an error (which it should at this point), but only give the last hint.

Would it be complicated to change the syntax, so the last example will give two hints as expected?

If, could
```
begin:hint
first hint
end:hint

begin:hint
second hint
end:hint
```
then also be allowed without too much hassle?

If, then we should get rid of the current `hint` with arguments syntax.

**Comment by iainbryson** [comment]
This can be done fairly easily, however it would be a breaking change -- all existing quizzes will fail to parse.

If that's OK, I'll make the change.  If not, then I can investigate accepting both syntaxes for a while and then invalidate the single-line hint later.

However, if we do that then it would make sense to have a new category of compile status, WARN, for issues which aren't errrors but need fixing.  That will be more expensive.

So we can:
(1) break the syntax now and accept only begin/end errors
(2) allow both begin/end and single line errors without warning
(3) allow both begin/end and single line errors and create an infrastructure for warnings.

Which would you prefer?  Cost increases as the numbers do ;)

**Comment by dtu-compute** [comment]
Excellent. No problem the current quizzes will fail. So please remove the old syntax as well.

So the WARN idea is for in the future to be able to change for format and still give good error messages?

If, then I have been thinking if we should have a version string in the quiz files, so the parser knows how to parse the file?

However I don't think we should be backwards compatible unless other universities uses the platform. Until then it is fine that we break the format each year. If we should end up having many quizzes that would break, then I would rather have we write a script that the professors can run on their desktop to convert from version 2016 to 2017 etc.
